Vagrant.configure("2") do |config|

  config.vm.box = "jhcook/macos-sierra"

  # Not working for some reason.
  config.vm.network "forwarded_port",
                    guest: 6045,
                    host: 8045,
                    host_ip: "127.0.0.1"

  config.vm.synced_folder "../..",
                          "/Users/vagrant/maker",
                          type: "rsync",
                          rsync__user: "vagrant",
                          rsync__group: "staff",
                          rsync__exclude: "webapp/node_modules/*"

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL
  SHELL

end
